//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidadPedagogicaSDStaticInfo.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UPSDTCUXEntities : DbContext
    {
        public UPSDTCUXEntities()
            : base("name=UPSDTCUXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mensajex> mensajex { get; set; }
        public virtual DbSet<usuariox> usuariox { get; set; }
        public virtual DbSet<tokens> tokens { get; set; }
    }
}
