//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidadPedagogicaSDStaticInfo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuariox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuariox()
        {
            this.mensajex = new HashSet<mensajex>();
        }
    
        public int idUsuario { get; set; }
        public string nombre { get; set; }
        public string pass { get; set; }
        public string cedula { get; set; }
        public Nullable<int> idRol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mensajex> mensajex { get; set; }
    }
}
